[tool.poetry]
name = "djabra"
version = "0.1.0"
description = ""
authors = ["Dwi Ahmad <dwi.hyuga@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
django = "^4.2.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
